export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
export const FILTER_POKEMONS_BY_NAME = 'FILTER_POKEMONS_BY_NAME';
export const FILTER_POKEMONS_BY_TYPE = 'FILTER_POKEMONS_BY_TYPE';
export const GET_POKEMON_BY_ID = 'GET_POKEMON_BY_ID';
